### ISSUE TITLE
修复与 excel 获取单元格内容操作有关的组件

### ISSUE THREAD

**Issue by coco-super** [coco-super/coco-super#19]
当 cell 格式为时间时，报错信息（测试组件为：透视表组件）：
```
Cannot convert object to primitive value
    at RpaProcess.constructor.runRPANode (C:\snapshot\suanpan\lib\rpaProcess.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```
![image](https://user-images.githubusercontent.com/48934955/119370206-9ba9dd00-bce7-11eb-8162-facdc8f55568.png)

**Comment by coco-super** [comment]
增强相关组件，添加配置项，允许用户获取单元格真实值/只读文本等..
https://stackoverflow.com/questions/17359835/what-is-the-difference-between-text-value-and-value2
